### PR TITLE
Add Thorchain Synth

### PR DESCRIPTION
**Pull request by junkai121**
Finished
- update `transfer`, `deposit`, `getTransactionData` for synth assets
In progress
- `getTransactions` the pagination is a problem.

### CODE REVIEW

**Comment by mikewyszinski** [comment]
picked this up today. merged latest from master and working on some added tests for supporting synths.

**Comment by DollyVolley** [comment]
> picked this up today. merged latest from master and working on some added tests for supporting synths.

How is it looking @mikewyszinski? Did you make any progress on that one?

**Comment by veado** [comment]
@DollyVolley Have you solved synth support in `xchain-thorchain` used by latest Brokkr https://app.brokkr.finance? If so, could you open a PR to bring it upstream, pls?

**Comment by veado** [comment]
Closing in favour of #475 + #476

**Pull request closed without merging**
