### PR TITLE
Thorchain.net as default explorer

### PR DESCRIPTION
**Pull request by 0xp3gasus**

### CODE REVIEW

**Review by juanfri-web3 — APPROVED** [review]

**Comment by Thorian1te** [comment]
just hold off on merging this. 
can we set our own default explorer?

**Review by Thorian1te — CHANGES_REQUESTED** [review]
Im not sure I want this change. Can we have a different solution to this. I prefer runescan to thorchain.net

**Comment by 0xp3gasus** [comment]
> Im not sure I want this change. Can we have a different solution to this. I prefer runescan to thorchain.net

We can change the approach. We can use Runescan as the default explorer and add the possibility to let users to use a custom one

**Comment by Thorian1te** [comment]
Yes, this would be useful indeed.

**Comment by GrassRootsCrypto** [comment]
> Im not sure I want this change. Can we have a different solution to this. I prefer runescan to thorchain.net

I agree. Can we just pause this one for now please.

**Pull request closed without merging**
